### ISSUE TITLE
building issues

### ISSUE THREAD

**Issue by Minecon724** [facebookresearch/craftassist#14]
https://www.youtube.com/watch?v=ofeldEf3M9w

**Comment by aszlam** [comment]
so this isn't a bug, in the sense its expected behavior of the current system, which will zealously try to match the schematic it is trying to build.  I do agree its a *failure* of the design current system (in particular the build task), and should be improved. In particular, there should be some mechanism for the bot to be able to change its plan based on what the player wants.  This can be really subtle and complicated; but at least, if the bot sees you trying to change the schematic as it builds, it could ask you if it should leave the blocks you place or destroy alone...  @Minecon724 You want to add it?  We will eventually otherwise

**Comment by kavyasrinet** [comment]
Hi @Minecon724 !
Checking in if @aszlam 's comment above helps.
We'd be happy to accept a PR if you are interested in implementing it.

**Comment by kavyasrinet** [comment]
Hi @Minecon724 !
We will be closing this issue for now.
We'll also be sending out a heads-up over email but we have now migrated the `craftassist` codebase to be here: https://github.com/facebookresearch/droidlet and we will be maintaining this repo going forward. We ask that you please switch to the `droidlet` repo going forward. 
Please feel free to reopen the issue under the `droidlet` repo if you still need help.
