### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by scatterp3** [facebookresearch/craftassist#18]
I have downloaded all the datasets but it is not specified how where to extract them
in order for the bot to gain this knowledge 

https://github.com/facebookresearch/craftassist#datasets

**Comment by kavyasrinet** [comment]
Hi @scatterp3 ,
Thanks for creating the issue.

The bot already uses models that have been trained on these datasets -- specifically the dialogue and the segmentation datasets. In addition, we have also released the house dataset that the bot currently doesn't use in any way  but can be used for research purposes. We published a [paper](http://openaccess.thecvf.com/content_ICCV_2019/papers/Chen_Order-Aware_Generative_Modeling_Using_the_3D-Craft_Dataset_ICCV_2019_paper.pdf) that trained a model on this dataset.

More detailed description of these datasets is described in our [framework paper](https://arxiv.org/abs/1907.08584).

That being said, you don't need to do anything additional with these datasets in order to set up the framework and play with the bot.

**Comment by kavyasrinet** [comment]
Hi @scatterp3 ,
Does the above answer your question ?

**Comment by scatterp** [comment]
yes thank you also for your information I read  paper that confirmed feeding baritone data works very well if you want more data that is (tested on mineml)

**Comment by kavyasrinet** [comment]
Great! thanks a lot.
Closing this issue for now but feel free to reopen / create a new issue if there are any followup questions.
