### ISSUE TITLE
Question about render?

### ISSUE THREAD

**Issue by banben** [facebookresearch/craftassist#42]
Hello, thanks for the great work. I can not find `minecraft_render/render.py` in this repo, but find `python/render_schematic.py` file use it to render chunky png, can you upload `minecraft_render` directory.

**Comment by snyxan** [comment]
Hi @banben, Thanks for creating this issue!

I've uploaded all related files to `python/minecraft_render` (except for ChunkyLauncher, reason explained in next paragraph). Please refer to [render.py](https://github.com/facebookresearch/craftassist/blob/master/python/minecraft_render/render.py#L55) to learn how to use it.

Note that we are using [Chunky](https://github.com/chunky-dev/chunky) to render minecraft world. For license issue we can not put their code inside our repo. Please download ChunkyLauncher [here](https://github.com/chunky-dev/chunky) and put it under python/minecraft_render in order to use the tool.

Let me know if you need any help.

**Comment by satyamedh** [comment]
@banben please close this :)

**Comment by kavyasrinet** [comment]
Closing this one out if there are no further questions :)
